<?php
$kniha = $this->data['kniha'];
$autor = $this->data["autori"][$kniha["id_aut"]-1];
?>

<div class="flex gap-10">

    <div class="w-1/3">
        <h1 class="text-xl font-bold mb-4"><?= $kniha['jmeno_knih'] ?></h1>
        <img src="uploads/<?= $kniha['id_knih'] ?>.jpg" alt="kniha" class="w-full]">
    </div>
    <div class="w-2/3 mt-10">
        <div class="flex gap-4">
            <div class="mt-2">Žánry:</div>
            <?php foreach ($this->data["zanry"] as $zanr):
                $checked = in_array($zanr['id_zanr'], $_GET['zanry'] ?? []) ? 'checked' : '';?>
                <div>
                    <div class="block px-2 py-1 text-white rounded-md <?=$zanr['bg_color']?>">
                        <?= $zanr["jmeno_zanr"] ?>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <div class="mt-6"><?= $kniha['obsah_knih'] ?></div>
        <div class="mt-10">
            <form>
                <div>
                    <label for="obsah_knih">Napiš komentář</label>
                    <textarea name="obsah_knih" id="obsah_knih" cols="30" rows="10" class="border rounded w-full p-4"></textarea>
                </div>
                <input
                        type="submit"
                        class="w-32 uppercase rounded bg-sky-600 text-white px-4 py-1.5 hover:cursor-pointer hover:bg-sky-700 transition"
                        value="Přidat"
                />
            </form>
            <div>
                <?php foreach ($this->data["zanry"] as $zanr):
                    $checked = in_array($zanr['id_zanr'], $_GET['zanry'] ?? []) ? 'checked' : '';?>
                    <div>
                        <div class="block px-2 py-1 text-white rounded-md <?=$zanr['bg_color']?>">
                            <?= $zanr["jmeno_zanr"] ?>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    </div>
</div>