<?php
$kniha = $this->data['kniha'];
$autor = $this->data["autori"][$kniha["id_aut"]-1];
?>

<div class="flex gap-10">

    <div class="w-1/3">
        <h1 class="text-xl font-bold mb-4"><?= $kniha['jmeno_knih'] ?></h1>
        <img src="uploads/<?= $kniha['id_knih'] ?>.jpg" alt="kniha" class="w-full]">
    </div>
    <div class="w-2/3 mt-10">
        <div class="flex gap-4">
            <div class="mt-2">Žánry:</div>
            <?php foreach ($this->data["zanry"] as $zanr):
                $checked = in_array($zanr['id_zanr'], $_GET['zanry'] ?? []) ? 'checked' : '';?>
                <div>
                    <div class="block px-2 py-1 text-white rounded-md <?=$zanr['bg_color']?>">
                        <?= $zanr["jmeno_zanr"] ?>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
        <div class="mt-6"><?= $kniha['obsah_knih'] ?></div>
    </div>
</div>