<form>
    <div class="relative mb-3 w-1/2">
        <input
            type="text"
            class=" peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 peer-focus:text-primary motion-reduce:transition-none dark:text-white dark:placeholder:text-neutral-300 dark:autofill:shadow-autofill dark:peer-focus:text-primary"
            id="vyhledavaniInput"
        />
        <label
            for="vyhledavaniInput"
            class="pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[1.6] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[0.9rem] peer-focus:scale-[0.8] peer-focus:text-primary  motion-reduce:transition-none dark:text-neutral-400 dark:peer-focus:text-primary"
        >Vyhledávání
        </label>
    </div>
    <input
        type="submit"
        class="w-32 uppercase rounded bg-sky-600 text-white px-4 py-1.5 hover:cursor-pointer hover:bg-sky-700 transition"
        value="Hledat"
    />
</form>