
<form class="w-full mx-auto flex" method="GET">
    <div class="w-1/4">
        <ul class="flex flex-col items-center gap-2">
            <?php  foreach ($this->data["zanry"] as $zanr):
                $checked = in_array($zanr['id_zanr'], $_GET['zanry'] ?? []) ? 'checked' : '';?>
                <li>
                    <button type="submit">
                        <input id="zanr<?= $zanr["id_zanr"] ?>" class="hidden peer" type="checkbox" name="zanry[]" value=<?= $zanr["id_zanr"] ?> <?= $checked ?>>
                        <label for="zanr<?= $zanr["id_zanr"] ?>" class="hover:cursor-pointer peer-checked:shadow-xl peer-checked:border-2 shadow-black block text-center w-24  py-1.5 text-white rounded-md <?=$zanr['bg_color']?>">
                            <?= $zanr["jmeno_zanr"] ?>
                        </label>
                    </button>
                </li>
            <?php endforeach;?>
        </ul>
    </div>
    <div class="w-3/4">
        <div class="flex flex-col items-center">
            <div class="relative mb-3 w-1/2">
                <input
                        type="text"
                        class=" peer block min-h-[auto] w-full rounded border bg-transparent px-3 py-[0.32rem] leading-[1.6] outline-none transition-all duration-200 ease-linear focus:placeholder:opacity-100 peer-focus:text-primary motion-reduce:transition-none dark:text-white dark:placeholder:text-neutral-300 dark:autofill:shadow-autofill dark:peer-focus:text-primary"
                        id="vyhledavaniInput"
                />
                <label
                        for="vyhledavaniInput"
                        class="pointer-events-none absolute left-3 top-0 mb-0 max-w-[90%] origin-[0_0] truncate pt-[0.37rem] leading-[1.6] text-neutral-500 transition-all duration-200 ease-out peer-focus:-translate-y-[0.9rem] peer-focus:scale-[0.8] peer-focus:text-primary  motion-reduce:transition-none dark:text-neutral-400 dark:peer-focus:text-primary"
                >Vyhledávání
                </label>
            </div>
            <input
                type="submit"
                class="w-32 uppercase rounded bg-sky-600 text-white px-4 py-1.5 hover:cursor-pointer hover:bg-sky-700 transition"
                value="Hledat"
            />
        </div>


        <div class="mt-4 grid grid-cols-3 items-center gap-4">
            <?php if (isset($this->data['knihy'])){
                foreach ($this->data["knihy"] as $kniha):
                    $autor = $this->data["autori"][$kniha["id_aut"]-1]?>
                    <a href="kniha/<?= $kniha["id_knih"] ?>">
                        <div class="flex flex-col items-center gap-2 border rounded py-5">

                                <img src="uploads/<?= $kniha["id_knih"] ?>.jpg" alt="obrazek" class="w-32 h-40">
                                <div class="text-center"><?= $kniha["jmeno_knih"] ?></div>
                                <div class="text-center"><?= $autor[1] ." ". $autor[2] ?></div>
                        </div>
                    </a>
                <?php endforeach;
            } ?>
        </div>

    </div>
</form>

